-- Generated from: Day_of_Data_Winnipeg_2026_Attendees_40554971420_20260914_161825_040.csv, report-2026-09-14T1013.csv, DayOfData_OranizersAndVolunteers.csv, speakerlist.csv
-- Idempotent ID rule: (Order ID * 100) + attendee sequence within that order.
-- Fill in @EventCode before executing this script.

DECLARE @EventCode uniqueidentifier = N'00000000-0000-0000-0000-000000000000';
DECLARE @EncryptionKey nvarchar(200) = N'';
DECLARE @Identities_blob nvarchar(max) = N'[
  {
    "id": "1541600395301",
    "firstName": "Oleksandr",
    "lastName": "Dimbrovskyi",
    "name": "Oleksandr Dimbrovskyi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "oleksandr.dimbrovskyi@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1543694209301",
    "firstName": "wilfred",
    "lastName": "kamau   wairimu",
    "name": "wilfred kamau   wairimu",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "samuelkariithi123@gmail.com",
    "location": "Nairobi, 30",
    "role": null
  },
  {
    "id": "1545925283301",
    "firstName": "Maria",
    "lastName": "Besiada",
    "name": "Maria Besiada",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "xrmeng720@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1545925283302",
    "firstName": "Xiaoran",
    "lastName": "Meng",
    "name": "Xiaoran Meng",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "xrmeng720@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1553574935301",
    "firstName": "Chiaka",
    "lastName": "Nosike",
    "name": "Chiaka Nosike",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "chiakanosike203@gmail.com",
    "location": "Toronto, ON",
    "role": null
  },
  {
    "id": "1553883222301",
    "firstName": "Juan",
    "lastName": "Villamizar",
    "name": "Juan Villamizar",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "jucamvil@hotmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1554162943301",
    "firstName": "Janelle Jaira",
    "lastName": "Mercado",
    "name": "Janelle Jaira Mercado",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "janjaimerc@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1555193018301",
    "firstName": "Richard",
    "lastName": "Essenyi",
    "name": "Richard Essenyi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ressenyi@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1558702137301",
    "firstName": "Tien",
    "lastName": "Huynh",
    "name": "Tien Huynh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "huynhntdl@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1558867735301",
    "firstName": "Scott",
    "lastName": "Stauffer",
    "name": "Scott Stauffer",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ScottAStauffer@Outlook.com",
    "location": "Surrey, BC",
    "role": "Speaker"
  },
  {
    "id": "1559291070301",
    "firstName": "Carson",
    "lastName": "Leung",
    "name": "Carson Leung",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "carson.leung@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559310127301",
    "firstName": "Lang",
    "lastName": "G",
    "name": "Lang G",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "gonglange@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559348056301",
    "firstName": "Princess",
    "lastName": "Cortes",
    "name": "Princess Cortes",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "pcortes@rrc.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559375850301",
    "firstName": "Armaan Singh",
    "lastName": "Grover",
    "name": "Armaan Singh Grover",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "armaans.grover07@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559394126301",
    "firstName": "Hitesh",
    "lastName": "Nagpal",
    "name": "Hitesh Nagpal",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "hiteshnagpal955@gmail.com",
    "location": "Calgary, AB",
    "role": null
  },
  {
    "id": "1559419620301",
    "firstName": "Zainab",
    "lastName": "Hassan",
    "name": "Zainab Hassan",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "zainabmosunmola@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559420234301",
    "firstName": "Ali",
    "lastName": "Esmaeili",
    "name": "Ali Esmaeili",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "a.programming2022@gmail.com",
    "location": "Montreal, QC",
    "role": null
  },
  {
    "id": "1559529675301",
    "firstName": "Adeleke",
    "lastName": "Adenuga",
    "name": "Adeleke Adenuga",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "agbolade2020@gmail.com",
    "location": "ON",
    "role": null
  },
  {
    "id": "1559549143301",
    "firstName": "Baher",
    "lastName": "Alabbar",
    "name": "Baher Alabbar",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "baher.alabbar@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559556560301",
    "firstName": "Kavya",
    "lastName": "Bakshi",
    "name": "Kavya Bakshi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "bakshikavya143@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559563226301",
    "firstName": "Ravneet",
    "lastName": "Kaur",
    "name": "Ravneet Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ravneet1994@gmail.com",
    "location": "Winnipeg, MB",
    "role": "Volunteer"
  },
  {
    "id": "1559599169301",
    "firstName": "Dapinder",
    "lastName": "Kaur",
    "name": "Dapinder Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "gilldapinder515@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559624007301",
    "firstName": "Laleh",
    "lastName": "Asadzadeh",
    "name": "Laleh Asadzadeh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "la.asadzadeh@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559629544301",
    "firstName": "Bisola",
    "lastName": "Adebija",
    "name": "Bisola Adebija",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "bisolaadebija@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559656166301",
    "firstName": "Amir",
    "lastName": "Bani Saeed",
    "name": "Amir Bani Saeed",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "banisaea@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559681575301",
    "firstName": "Yang",
    "lastName": "Liu",
    "name": "Yang Liu",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "liuyang6093@gmail.com",
    "location": "Winnipeg, MB",
    "role": "Volunteer"
  },
  {
    "id": "1559692282301",
    "firstName": "Khadijat",
    "lastName": "Folarin",
    "name": "Khadijat Folarin",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "folarinko20@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559746442301",
    "firstName": "Scott",
    "lastName": "White",
    "name": "Scott White",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "7qwfk8pznm@privaterelay.appleid.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1559968138301",
    "firstName": "Natasha",
    "lastName": "Williams",
    "name": "Natasha Williams",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "natashawilliams883@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560012182301",
    "firstName": "Zahra",
    "lastName": "Nasresfahani",
    "name": "Zahra Nasresfahani",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "nasresfz@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560020388301",
    "firstName": "Zahra",
    "lastName": "Rizvi",
    "name": "Zahra Rizvi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "zahraxrizvi@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560024139301",
    "firstName": "Gurdarshan",
    "lastName": "Singh",
    "name": "Gurdarshan Singh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "singhgurdarshan715@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560025894301",
    "firstName": "Bagdat",
    "lastName": "Rakhimov",
    "name": "Bagdat Rakhimov",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "bagdat.rakhimov@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560025914301",
    "firstName": "Kurt",
    "lastName": "Huff",
    "name": "Kurt Huff",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "kurtljhuff@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560029003301",
    "firstName": "Jay",
    "lastName": "Dalool",
    "name": "Jay Dalool",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "jay16ca@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560055968301",
    "firstName": "Fawaz",
    "lastName": "Bin Saleem",
    "name": "Fawaz Bin Saleem",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "fawazbinsaleem2001@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560065224301",
    "firstName": "McCauley",
    "lastName": "Armishaw",
    "name": "McCauley Armishaw",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "mtarmishaw14@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560071352301",
    "firstName": "Emmanuel",
    "lastName": "Oyenuga",
    "name": "Emmanuel Oyenuga",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "emmaoyenuga@gmail.com",
    "location": "BC",
    "role": "Volunteer"
  },
  {
    "id": "1560075501301",
    "firstName": "Atishaya",
    "lastName": "Maharjan",
    "name": "Atishaya Maharjan",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "atishaya7777@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560116371301",
    "firstName": "Yirong",
    "lastName": "Wang",
    "name": "Yirong Wang",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "yw181920@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560117712301",
    "firstName": "Roshan",
    "lastName": "Chapagain",
    "name": "Roshan Chapagain",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "arobce@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560155242301",
    "firstName": "Simran",
    "lastName": "Panthi",
    "name": "Simran Panthi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "simranpanthi101@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560160030301",
    "firstName": "Faiza",
    "lastName": "Salami",
    "name": "Faiza Salami",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "salami.faiza15@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560224997301",
    "firstName": "Ramatjyot",
    "lastName": "Singh",
    "name": "Ramatjyot Singh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ramatjyot13.ca@gmail.com",
    "location": "ON",
    "role": null
  },
  {
    "id": "1560226919301",
    "firstName": "Abdalla",
    "lastName": "Mohammed",
    "name": "Abdalla Mohammed",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "abdalla.mohd000@gmail.com",
    "location": "Etobicoke, ON",
    "role": null
  },
  {
    "id": "1560250008301",
    "firstName": "Kimi",
    "lastName": "Lin",
    "name": "Kimi Lin",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "kimibusiness@gmail.com",
    "location": "Etobicoke, ON",
    "role": null
  },
  {
    "id": "1560320034301",
    "firstName": "Pratham",
    "lastName": "Patel",
    "name": "Pratham Patel",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "adriftenigma@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560334536301",
    "firstName": "Gurneet",
    "lastName": "Kaur",
    "name": "Gurneet Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "kgurneet0224@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560423606301",
    "firstName": "Atul",
    "lastName": "Jha",
    "name": "Atul Jha",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ashandilya795@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560424807301",
    "firstName": "Shey",
    "lastName": "Porto",
    "name": "Shey Porto",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "sherylsuarezporto@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560492678301",
    "firstName": "Pam",
    "lastName": "Mollinedo",
    "name": "Pam Mollinedo",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "pamkmoll@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560536069301",
    "firstName": "Hasib",
    "lastName": "Pulok",
    "name": "Hasib Pulok",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ahsanpulok999@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560586553301",
    "firstName": "Kismat",
    "lastName": "Ali",
    "name": "Kismat Ali",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "Alikismat2222@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560763969301",
    "firstName": "Logan",
    "lastName": "Decock",
    "name": "Logan Decock",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "logandecock004@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560790071301",
    "firstName": "Obafunsho",
    "lastName": "Thanni",
    "name": "Obafunsho Thanni",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "obafunshot@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560845800301",
    "firstName": "Kiet",
    "lastName": "QUach",
    "name": "Kiet QUach",
    "description": "ESDC",
    "jobTitle": "Senior Data Analyst",
    "phone": "",
    "email": "kquach@gmail.com",
    "location": "Ottawa, ON",
    "role": null
  },
  {
    "id": "1560847292301",
    "firstName": "jian",
    "lastName": "chen",
    "name": "jian chen",
    "description": "outreachgenius",
    "jobTitle": "",
    "phone": "",
    "email": "alanchenjain@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560859437301",
    "firstName": "Brenda",
    "lastName": "Stoesz",
    "name": "Brenda Stoesz",
    "description": "University of Manitoba",
    "jobTitle": "Portfolio Lead - Data, Evaluation, and Higher Education Research",
    "phone": "",
    "email": "brenda.stoesz@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560860972301",
    "firstName": "Viktoriia",
    "lastName": "Pylypets-Romaniuk",
    "name": "Viktoriia Pylypets-Romaniuk",
    "description": "Outlier",
    "jobTitle": "Data analyst",
    "phone": "",
    "email": "prviktoriia@gmail.com",
    "location": "Steinbach, MB",
    "role": null
  },
  {
    "id": "1560877241301",
    "firstName": "Mandy",
    "lastName": "Siragusa",
    "name": "Mandy Siragusa",
    "description": "University of Manitoba, Office of Rural and Remote Learner Experiences",
    "jobTitle": "",
    "phone": "",
    "email": "mandy.siragusa@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560905042301",
    "firstName": "Morgan",
    "lastName": "May",
    "name": "Morgan May",
    "description": "University of Manitoba - Engineering Makerspace",
    "jobTitle": "Maker of things, writer of codes, breaker of systems",
    "phone": "",
    "email": "morgan.may2@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1560920322301",
    "firstName": "Noel",
    "lastName": "Gelineau",
    "name": "Noel Gelineau",
    "description": "Manitoba Liquor and Lotteries Corporation",
    "jobTitle": "Data Governance Architect",
    "phone": "",
    "email": "noel.gelineau@gmail.com",
    "location": "Niverville, MB",
    "role": null
  },
  {
    "id": "1560948260301",
    "firstName": "Binita",
    "lastName": "Shetty",
    "name": "Binita Shetty",
    "description": "University of Manitoba",
    "jobTitle": "Senior Analyst",
    "phone": "",
    "email": "Shettyb@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561032486301",
    "firstName": "Andrey",
    "lastName": "Rybak",
    "name": "Andrey Rybak",
    "description": "Hrove labs",
    "jobTitle": "Founder",
    "phone": "",
    "email": "naonennenets@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561052450301",
    "firstName": "Olivia",
    "lastName": "Lee",
    "name": "Olivia Lee",
    "description": "University of Manitoba",
    "jobTitle": "Researcher",
    "phone": "",
    "email": "olivia.lee@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561085718301",
    "firstName": "Marcus",
    "lastName": "Hlady",
    "name": "Marcus Hlady",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "hlady.marcus@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561086958301",
    "firstName": "Gurrajan",
    "lastName": "Sharma",
    "name": "Gurrajan Sharma",
    "description": "Faculty of Science",
    "jobTitle": "Student",
    "phone": "",
    "email": "shar179@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561099062301",
    "firstName": "Karen",
    "lastName": "Masambaji",
    "name": "Karen Masambaji",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "karenupendo@gmail.com",
    "location": "",
    "role": null
  },
  {
    "id": "1561106479301",
    "firstName": "Janette",
    "lastName": "Suherli",
    "name": "Janette Suherli",
    "description": "University of Manitoba",
    "jobTitle": "Graduate Student",
    "phone": "",
    "email": "suherlij@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561108722301",
    "firstName": "Anthony",
    "lastName": "Okolie",
    "name": "Anthony Okolie",
    "description": "N/a",
    "jobTitle": "",
    "phone": "",
    "email": "anthonyokolie.ace@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561207709301",
    "firstName": "Nicholas",
    "lastName": "Tan",
    "name": "Nicholas Tan",
    "description": "UofM student",
    "jobTitle": "Student",
    "phone": "",
    "email": "tannjh@myumanitoba.ca",
    "location": "Singapore",
    "role": null
  },
  {
    "id": "1561273694301",
    "firstName": "Minori",
    "lastName": "Shibuya",
    "name": "Minori Shibuya",
    "description": "Uofm",
    "jobTitle": "Student",
    "phone": "",
    "email": "zibanyan1222@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561278334301",
    "firstName": "Jatinder",
    "lastName": "Sahota",
    "name": "Jatinder Sahota",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "jatindersahota2184@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561291694301",
    "firstName": "Jeet",
    "lastName": "Rajvanshi",
    "name": "Jeet Rajvanshi",
    "description": "student",
    "jobTitle": "",
    "phone": "",
    "email": "jeetdhruv2003@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561474878301",
    "firstName": "Gurjit",
    "lastName": "Singh",
    "name": "Gurjit Singh",
    "description": "NA",
    "jobTitle": "PMO Manager",
    "phone": "",
    "email": "guruhayat@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561504465301",
    "firstName": "Amro",
    "lastName": "Hamid",
    "name": "Amro Hamid",
    "description": "N''Dinawemak",
    "jobTitle": "Digital Transformation and Operations Excellence Manager",
    "phone": "",
    "email": "alshukairi.al@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561536712301",
    "firstName": "Chidiebere Gregory",
    "lastName": "Uduh",
    "name": "Chidiebere Gregory Uduh",
    "description": "Bejite",
    "jobTitle": "DevOps Lead",
    "phone": "",
    "email": "udugreg@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561539580301",
    "firstName": "Seyedsaber",
    "lastName": "Mirmiran",
    "name": "Seyedsaber Mirmiran",
    "description": "University of Manitoba",
    "jobTitle": "Application Developer",
    "phone": "",
    "email": "seyedsaber.mirmiran@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561541794301",
    "firstName": "Mohammad",
    "lastName": "Hassan",
    "name": "Mohammad Hassan",
    "description": "University of Winnipeg",
    "jobTitle": "Research Assistant",
    "phone": "",
    "email": "hasan.ahmed1435@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561593626301",
    "firstName": "Sofia",
    "lastName": "Dumas",
    "name": "Sofia Dumas",
    "description": "IG Wealth Management",
    "jobTitle": "Software Developer",
    "phone": "",
    "email": "dumas.mariasofia@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561597058301",
    "firstName": "Shivanshu",
    "lastName": "Sharma",
    "name": "Shivanshu Sharma",
    "description": "Price Industries",
    "jobTitle": "Data Engineer",
    "phone": "",
    "email": "shivanshu.mps@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561598801301",
    "firstName": "Ramandeep",
    "lastName": "Kaur",
    "name": "Ramandeep Kaur",
    "description": "University of Manitoba",
    "jobTitle": "Database and Reporting Analyst",
    "phone": "",
    "email": "Ramandeep.Kaur1@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561601890301",
    "firstName": "Anika",
    "lastName": "Viado",
    "name": "Anika Viado",
    "description": "Red River College (Student)",
    "jobTitle": "Student",
    "phone": "",
    "email": "anikaviado@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561605395301",
    "firstName": "Vanessa",
    "lastName": "Castro",
    "name": "Vanessa Castro",
    "description": "Red River Polytechnic College - Student",
    "jobTitle": "Student",
    "phone": "",
    "email": "ayla.buenafe88@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561605545301",
    "firstName": "Vance Alden",
    "lastName": "Castro",
    "name": "Vance Alden Castro",
    "description": "Red River College Polytechnic",
    "jobTitle": "Student",
    "phone": "",
    "email": "vcastro2@rrc.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561612659301",
    "firstName": "Tatiana",
    "lastName": "Varlamova",
    "name": "Tatiana Varlamova",
    "description": "Norima Consulting",
    "jobTitle": "",
    "phone": "",
    "email": "varlamova.com@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561612816301",
    "firstName": "Oleksiy",
    "lastName": "Dolgykh",
    "name": "Oleksiy Dolgykh",
    "description": "Individual Researcher",
    "jobTitle": "AI/ML Researcher/Manager",
    "phone": "",
    "email": "alexey.dolgich@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561621631301",
    "firstName": "Utsav",
    "lastName": "Panchal",
    "name": "Utsav Panchal",
    "description": "Manitoba Public Insurance",
    "jobTitle": "Supervisor - Cloud Infrastructure",
    "phone": "",
    "email": "utpanc@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561628903301",
    "firstName": "Sarabjit",
    "lastName": "Sethi",
    "name": "Sarabjit Sethi",
    "description": "MPI",
    "jobTitle": "Data Transformation Specialist",
    "phone": "",
    "email": "sarabjitsinghsethi85@gmail.com",
    "location": "ON",
    "role": null
  },
  {
    "id": "1561659482301",
    "firstName": "Mariya",
    "lastName": "Salamatova",
    "name": "Mariya Salamatova",
    "description": "Bird Construction",
    "jobTitle": "Senior Data Architect",
    "phone": "",
    "email": "salmarnic@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1561671324301",
    "firstName": "Gustavo",
    "lastName": "Dayrell",
    "name": "Gustavo Dayrell",
    "description": "IG Financial",
    "jobTitle": "Data Engineering Specialist",
    "phone": "",
    "email": "gusdayrell@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561676708301",
    "firstName": "Ali",
    "lastName": "Rezaei",
    "name": "Ali Rezaei",
    "description": "Manitoba Hydro",
    "jobTitle": "Load Forecast specialist",
    "phone": "",
    "email": "ali.rezaei.ee@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1561680804301",
    "firstName": "Shehani",
    "lastName": "Ranasinghe",
    "name": "Shehani Ranasinghe",
    "description": "Red River college",
    "jobTitle": "Student",
    "phone": "",
    "email": "shehanidinithi89@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1561682321301",
    "firstName": "Tuan",
    "lastName": "Le Dinh",
    "name": "Tuan Le Dinh",
    "description": "IG Wealth Management",
    "jobTitle": "Data Engineering Specialist",
    "phone": "",
    "email": "9fkws8czsy@privaterelay.appleid.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561703115301",
    "firstName": "Sohvat",
    "lastName": "Saini",
    "name": "Sohvat Saini",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "sainis2@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561703502301",
    "firstName": "Simi",
    "lastName": "Adeniyi",
    "name": "Simi Adeniyi",
    "description": "Student",
    "jobTitle": "",
    "phone": "",
    "email": "simiadeniyi97@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561723010301",
    "firstName": "Sethulakshmi",
    "lastName": "K Sajeev",
    "name": "Sethulakshmi K Sajeev",
    "description": "University of Manitoba",
    "jobTitle": "Research Analyst",
    "phone": "",
    "email": "seth.kumbalathuparambilsajeev@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561793106301",
    "firstName": "Pegah",
    "lastName": "Geranmayehkashani",
    "name": "Pegah Geranmayehkashani",
    "description": "Price Industries",
    "jobTitle": "",
    "phone": "",
    "email": "pegah.geranmayeh@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561805494301",
    "firstName": "Swastik",
    "lastName": "Dash",
    "name": "Swastik Dash",
    "description": "Student at University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "helloswastikdash@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561810993301",
    "firstName": "Byron",
    "lastName": "Wright",
    "name": "Byron Wright",
    "description": "Asper School of Business - U of M",
    "jobTitle": "MIS Instructor",
    "phone": "",
    "email": "byron.wright@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561850122301",
    "firstName": "Sai Sumanth",
    "lastName": "Mellacheruvu",
    "name": "Sai Sumanth Mellacheruvu",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "sumanthmellacheruvu@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561851119301",
    "firstName": "Emily",
    "lastName": "Clyde-Parry Yaroszko",
    "name": "Emily Clyde-Parry Yaroszko",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "yaroszko@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561868662301",
    "firstName": "Thuan Khang",
    "lastName": "Dinh",
    "name": "Thuan Khang Dinh",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "matthuanphong@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561894925301",
    "firstName": "Shelly",
    "lastName": "Smith",
    "name": "Shelly Smith",
    "description": "ARMA Canada",
    "jobTitle": "Information and Privacy Manager",
    "phone": "",
    "email": "shellybsmith@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561900576301",
    "firstName": "Arturo",
    "lastName": "Barrios",
    "name": "Arturo Barrios",
    "description": "Enalta",
    "jobTitle": "",
    "phone": "",
    "email": "abarriosdc@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561911048301",
    "firstName": "Subhash",
    "lastName": "Yadav",
    "name": "Subhash Yadav",
    "description": "university of manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "yadavs2@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1561913300301",
    "firstName": "Faith",
    "lastName": "Akinyemi",
    "name": "Faith Akinyemi",
    "description": "GOM",
    "jobTitle": "",
    "phone": "",
    "email": "faithakinyemi01@gmail.com",
    "location": "Calgary, AB",
    "role": null
  },
  {
    "id": "1562012658301",
    "firstName": "Emma",
    "lastName": "Yang",
    "name": "Emma Yang",
    "description": "princessauto",
    "jobTitle": "",
    "phone": "",
    "email": "fxyflttw@hotmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1562103995301",
    "firstName": "Daniel",
    "lastName": "Mai",
    "name": "Daniel Mai",
    "description": "PolicyMe",
    "jobTitle": "",
    "phone": "",
    "email": "danielmai12.cs@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562252172301",
    "firstName": "Moon Jung",
    "lastName": "PERSSON",
    "name": "Moon Jung PERSSON",
    "description": "MB HYDRO",
    "jobTitle": "Tech. Assistance",
    "phone": "",
    "email": "ypersson@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562260224301",
    "firstName": "Erik",
    "lastName": "Persson",
    "name": "Erik Persson",
    "description": "Mvsd",
    "jobTitle": "Educator",
    "phone": "",
    "email": "espersson@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562331685301",
    "firstName": "Christopher",
    "lastName": "Duguay",
    "name": "Christopher Duguay",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "umdugua2@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562358005301",
    "firstName": "Navroop",
    "lastName": "Kaur",
    "name": "Navroop Kaur",
    "description": "RRC Polytechnic",
    "jobTitle": "Student",
    "phone": "",
    "email": "navroopkaur26@yahoo.com",
    "location": "Winnipeg, MB",
    "role": "Volunteer"
  },
  {
    "id": "1562448071301",
    "firstName": "Edwin Josue",
    "lastName": "Saltos Narvaez",
    "name": "Edwin Josue Saltos Narvaez",
    "description": "RRC",
    "jobTitle": "IT",
    "phone": "",
    "email": "esaltosnarvaez@academic.rrc.ca",
    "location": "Montreal, QC",
    "role": null
  },
  {
    "id": "1562584454301",
    "firstName": "KEIKO",
    "lastName": "HURTADO ANAMPA",
    "name": "KEIKO HURTADO ANAMPA",
    "description": "Student",
    "jobTitle": "Business intelligence analyst",
    "phone": "",
    "email": "hurtadok@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562590552301",
    "firstName": "Demisew",
    "lastName": "Mengistu",
    "name": "Demisew Mengistu",
    "description": "WCB Manitoba",
    "jobTitle": "cloud engineer",
    "phone": "",
    "email": "mailtodemis08@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1562609928301",
    "firstName": "Ian",
    "lastName": "Smith",
    "name": "Ian Smith",
    "description": "Payworks",
    "jobTitle": "",
    "phone": "",
    "email": "ian.smith.12a@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562615225301",
    "firstName": "Evan",
    "lastName": "Penner",
    "name": "Evan Penner",
    "description": "Aimsio",
    "jobTitle": "Software Developer",
    "phone": "",
    "email": "evan.penner@aimsio.com",
    "location": "Kleefeld, MB",
    "role": null
  },
  {
    "id": "1562618106301",
    "firstName": "Ghazanfar",
    "lastName": "Abidi",
    "name": "Ghazanfar Abidi",
    "description": "Exchange Technology Services",
    "jobTitle": "Director Business Intelligence",
    "phone": "",
    "email": "ghazanfarjawed@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562621035301",
    "firstName": "Chris",
    "lastName": "Mac",
    "name": "Chris Mac",
    "description": "RRC Polytech",
    "jobTitle": "Instructor",
    "phone": "",
    "email": "chris@macmac.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562625614301",
    "firstName": "Mathieu",
    "lastName": "Sawatzky",
    "name": "Mathieu Sawatzky",
    "description": "Stride Credit Union",
    "jobTitle": "Data Analyst",
    "phone": "",
    "email": "matsawatzky@gmail.com",
    "location": "Toronto, ON",
    "role": null
  },
  {
    "id": "1562626086301",
    "firstName": "Barakat",
    "lastName": "Akinsanya-Fadairo",
    "name": "Barakat Akinsanya-Fadairo",
    "description": "WRHA",
    "jobTitle": "Business Analyst",
    "phone": "",
    "email": "bakkyinspiration@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562630002301",
    "firstName": "Upneesh",
    "lastName": "Thakur",
    "name": "Upneesh Thakur",
    "description": "Exchange Technology Services",
    "jobTitle": "Manager, Analytics",
    "phone": "",
    "email": "uthakur@exchangetech.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562642121301",
    "firstName": "Spencer",
    "lastName": "McDonald",
    "name": "Spencer McDonald",
    "description": "EPLS Group",
    "jobTitle": "IT Manager",
    "phone": "",
    "email": "spencer.c.mcdonald@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562644561301",
    "firstName": "Ashlean",
    "lastName": "Sterling",
    "name": "Ashlean Sterling",
    "description": "ByAshlean",
    "jobTitle": "Freelancer",
    "phone": "",
    "email": "ashlean.sterling@icloud.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562670906301",
    "firstName": "Gabriel",
    "lastName": "Nazario",
    "name": "Gabriel Nazario",
    "description": "Oag mb",
    "jobTitle": "Data analyst manager",
    "phone": "",
    "email": "nazariogabrielfarias@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562698709301",
    "firstName": "Nima",
    "lastName": "Geran Malek",
    "name": "Nima Geran Malek",
    "description": "Micro Tools & Machines",
    "jobTitle": "Manufacturing Engineer",
    "phone": "",
    "email": "nima.geran@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562745463301",
    "firstName": "Harshvardhan",
    "lastName": "Gadhavi",
    "name": "Harshvardhan Gadhavi",
    "description": "Pearle Vision",
    "jobTitle": "sales associate",
    "phone": "",
    "email": "harshvardhan@gadhvi.xyz",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562746922301",
    "firstName": "Cyril",
    "lastName": "Li",
    "name": "Cyril Li",
    "description": "Student",
    "jobTitle": "Student",
    "phone": "",
    "email": "cyrils.li@icloud.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562767859301",
    "firstName": "Guadalupe",
    "lastName": "Ricagno",
    "name": "Guadalupe Ricagno",
    "description": "Red River Mutual",
    "jobTitle": "HR Analytics",
    "phone": "",
    "email": "gricagno@redrivermutual.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562786892301",
    "firstName": "Kyle",
    "lastName": "Bain",
    "name": "Kyle Bain",
    "description": "Johnston Group",
    "jobTitle": "Manager, Data & Analytics",
    "phone": "",
    "email": "kylejennb@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1562957600301",
    "firstName": "Farzana",
    "lastName": "Ebrahim",
    "name": "Farzana Ebrahim",
    "description": "University of Manitoba",
    "jobTitle": "Senior Developer, Digital Learning Environments",
    "phone": "",
    "email": "farzana.ebrahim@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563000108301",
    "firstName": "Lealdo",
    "lastName": "Andrade",
    "name": "Lealdo Andrade",
    "description": "Intouch Insight",
    "jobTitle": "",
    "phone": "",
    "email": "lealdo.gois.andrade@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563027544301",
    "firstName": "Nathan",
    "lastName": "Da Silva",
    "name": "Nathan Da Silva",
    "description": "Chico''s Computers",
    "jobTitle": "Owner/Lead Technician",
    "phone": "",
    "email": "nathan.dasilva@hotmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563227158301",
    "firstName": "Arthur",
    "lastName": "Rangel",
    "name": "Arthur Rangel",
    "description": "Personal",
    "jobTitle": "ThinkLeader",
    "phone": "",
    "email": "yizus.rangel@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1563358415301",
    "firstName": "Kijandi Pierre",
    "lastName": "Niyungeko",
    "name": "Kijandi Pierre Niyungeko",
    "description": "Pierre PC Repair Inc.",
    "jobTitle": "IT Support Specialist",
    "phone": "",
    "email": "pierrekijandi@hotmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563510519301",
    "firstName": "Peter",
    "lastName": "Vu",
    "name": "Peter Vu",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "peter.vu298@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563642957301",
    "firstName": "Andrea",
    "lastName": "Sanchez",
    "name": "Andrea Sanchez",
    "description": "Freelancer",
    "jobTitle": "Microsoft Data Analyst - AzureDataFactory, with 5 years of experience in the Mic",
    "phone": "",
    "email": "andrealsanchez2018@gmail.com",
    "location": "Calgary, AB",
    "role": null
  },
  {
    "id": "1563775590301",
    "firstName": "Fatimah",
    "lastName": "Salami",
    "name": "Fatimah Salami",
    "description": "Kpmg",
    "jobTitle": "",
    "phone": "",
    "email": "fatimah.salami@gmail.com",
    "location": "ON",
    "role": null
  },
  {
    "id": "1563891420301",
    "firstName": "Steffen",
    "lastName": "Walker",
    "name": "Steffen Walker",
    "description": "Red River College Polytechnic",
    "jobTitle": "Student",
    "phone": "",
    "email": "swbusinesscontact10@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563963221301",
    "firstName": "Richard",
    "lastName": "Chan",
    "name": "Richard Chan",
    "description": "Manitoba Hydro",
    "jobTitle": "",
    "phone": "",
    "email": "0be9nsdxc@mozmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563965593301",
    "firstName": "YaWen",
    "lastName": "Huang",
    "name": "YaWen Huang",
    "description": "DAX",
    "jobTitle": "",
    "phone": "",
    "email": "yawen299@hotmail.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563967292301",
    "firstName": "Dilawer",
    "lastName": "Hussain",
    "name": "Dilawer Hussain",
    "description": "onghost.com",
    "jobTitle": "Co-founder @ onghost.com",
    "phone": "",
    "email": "dilaw3r@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563969818301",
    "firstName": "Hamza",
    "lastName": "H",
    "name": "Hamza H",
    "description": "Fatir Consulting",
    "jobTitle": "",
    "phone": "",
    "email": "hamzahaque30@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563970946301",
    "firstName": "Saba",
    "lastName": "S",
    "name": "Saba S",
    "description": "None",
    "jobTitle": "",
    "phone": "",
    "email": "saba@ymail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563972624301",
    "firstName": "Melanie",
    "lastName": "Gallajones",
    "name": "Melanie Gallajones",
    "description": "Student",
    "jobTitle": "Student",
    "phone": "",
    "email": "mcgallajones@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1563977639301",
    "firstName": "Jen",
    "lastName": "Adriano",
    "name": "Jen Adriano",
    "description": "New Flyer Industries",
    "jobTitle": "Data Science and Applications Development Lead",
    "phone": "",
    "email": "jrjavier13@yahoo.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564014110301",
    "firstName": "Jeremy",
    "lastName": "Malenchak",
    "name": "Jeremy Malenchak",
    "description": "DAX Digital Technologies Inc.",
    "jobTitle": "Product Lead",
    "phone": "",
    "email": "jeremytnmalenchak@gmail.com",
    "location": "Tokyo, 13",
    "role": null
  },
  {
    "id": "1564017447301",
    "firstName": "Jawaher",
    "lastName": "Chowdhury",
    "name": "Jawaher Chowdhury",
    "description": "Al Hijra Islamic School",
    "jobTitle": "Classroom Teacher",
    "phone": "",
    "email": "jawaherakhter498@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564035592301",
    "firstName": "Fangyuan",
    "lastName": "Chen",
    "name": "Fangyuan Chen",
    "description": "None",
    "jobTitle": "N/A",
    "phone": "",
    "email": "videopostproduction@outlook.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564083986301",
    "firstName": "Madison",
    "lastName": "Fehr",
    "name": "Madison Fehr",
    "description": "DAX Digital Technologies Inc.",
    "jobTitle": "Frontend Developer",
    "phone": "",
    "email": "madisonfehr@icloud.com",
    "location": "Tokyo, 13",
    "role": null
  },
  {
    "id": "1564195963301",
    "firstName": "Artem",
    "lastName": "Ramus",
    "name": "Artem Ramus",
    "description": "MCI",
    "jobTitle": "Analyst",
    "phone": "",
    "email": "artem.ramus@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564218521301",
    "firstName": "Kurt",
    "lastName": "Shaw",
    "name": "Kurt Shaw",
    "description": "New Flyer",
    "jobTitle": "Director Manufacturing Business Systems",
    "phone": "",
    "email": "kurt_shaw@newflyer.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564218815301",
    "firstName": "Erwin",
    "lastName": "Lopez",
    "name": "Erwin Lopez",
    "description": "Motor Coach Industries",
    "jobTitle": "Data Analyst",
    "phone": "",
    "email": "erwin.lopez@mcicoach.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564219220301",
    "firstName": "RITHIKA",
    "lastName": "NEMURI",
    "name": "RITHIKA NEMURI",
    "description": "inTouch CX",
    "jobTitle": "Technical Support Representative",
    "phone": "",
    "email": "rithika.nemuri@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564219596301",
    "firstName": "Joy",
    "lastName": "Chand",
    "name": "Joy Chand",
    "description": "Wawanesa Insurance",
    "jobTitle": "Manager, Advanced Analytics",
    "phone": "",
    "email": "jchand@wawanesa.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564219904301",
    "firstName": "RAJESH",
    "lastName": "KOTHAPETA",
    "name": "RAJESH KOTHAPETA",
    "description": "NEW FLYER INDUSTRIES",
    "jobTitle": "Junior Electrical Designer",
    "phone": "",
    "email": "rajesh_kothapeta@newflyer.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564224261301",
    "firstName": "Bradley",
    "lastName": "Crass",
    "name": "Bradley Crass",
    "description": "Pathfinder Biotechnology Solutions Inc.",
    "jobTitle": "Founder, CEO",
    "phone": "",
    "email": "talktoBrad9002@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564316617301",
    "firstName": "Sara",
    "lastName": "Cianflone",
    "name": "Sara Cianflone",
    "description": "University of Manitoba",
    "jobTitle": "Project Manager",
    "phone": "",
    "email": "Sara.Cianflone@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564323383301",
    "firstName": "Katie",
    "lastName": "Sanders",
    "name": "Katie Sanders",
    "description": "Optimiz",
    "jobTitle": "Observability Engineer",
    "phone": "",
    "email": "ksanders5728@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564342598301",
    "firstName": "Khang",
    "lastName": "Duong",
    "name": "Khang Duong",
    "description": "University of Manitoba",
    "jobTitle": "Graduate Researcher",
    "phone": "",
    "email": "duongk5@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564342665301",
    "firstName": "Niloofar",
    "lastName": "Raeispour",
    "name": "Niloofar Raeispour",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "raeispon@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564343247301",
    "firstName": "BARDIA",
    "lastName": "EGHBALNIA",
    "name": "BARDIA EGHBALNIA",
    "description": "FWS GROUP",
    "jobTitle": "",
    "phone": "",
    "email": "beghbalnia@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564344327301",
    "firstName": "Sahej",
    "lastName": "Garg",
    "name": "Sahej Garg",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "sahejgarg2018@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564350106301",
    "firstName": "Allison",
    "lastName": "Ferguson",
    "name": "Allison Ferguson",
    "description": "Turasanna Inc.",
    "jobTitle": "Co-Founder",
    "phone": "",
    "email": "farbinkie@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564353719301",
    "firstName": "Tamir",
    "lastName": "Tarom",
    "name": "Tamir Tarom",
    "description": "Johnston group",
    "jobTitle": "Data Engineer",
    "phone": "",
    "email": "ttarom1987@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564360513301",
    "firstName": "Soleiman",
    "lastName": "Hosseinpour",
    "name": "Soleiman Hosseinpour",
    "description": "University of Manitoba",
    "jobTitle": "Ph.D researcher",
    "phone": "",
    "email": "soleiman.hosseinpour@gmail.com",
    "location": "ON",
    "role": null
  },
  {
    "id": "1564386372301",
    "firstName": "Aseem",
    "lastName": "Shaikh",
    "name": "Aseem Shaikh",
    "description": "Lets Give Together",
    "jobTitle": "",
    "phone": "",
    "email": "aseem@letsgivetogether.com",
    "location": "Morden, MB",
    "role": null
  },
  {
    "id": "1564387885301",
    "firstName": "Evelyn",
    "lastName": "Zhang",
    "name": "Evelyn Zhang",
    "description": "Let''s Give Together",
    "jobTitle": "Data & Systems Specialist",
    "phone": "",
    "email": "yhzwpg@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564388528301",
    "firstName": "Daniel",
    "lastName": "Melo",
    "name": "Daniel Melo",
    "description": "New Flyer",
    "jobTitle": "Data Scientist",
    "phone": "",
    "email": "daniel.melo.castiblanco@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564423402301",
    "firstName": "Roxana",
    "lastName": "Ibanez",
    "name": "Roxana Ibanez",
    "description": "Winnipeg Economic Development and Tourism",
    "jobTitle": "",
    "phone": "",
    "email": "roxana@winnipegedt.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564427218301",
    "firstName": "Boluwatife",
    "lastName": "Akintola",
    "name": "Boluwatife Akintola",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "akintolb@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564442049301",
    "firstName": "Neelofar",
    "lastName": "vahora",
    "name": "Neelofar vahora",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "vneelofar@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564457374301",
    "firstName": "Jing",
    "lastName": "Jing",
    "name": "Jing Jing",
    "description": "HMLC",
    "jobTitle": "",
    "phone": "",
    "email": "jj.czgm@gmail.com",
    "location": "ON",
    "role": null
  },
  {
    "id": "1564526538301",
    "firstName": "Naod",
    "lastName": "Tedros",
    "name": "Naod Tedros",
    "description": "0",
    "jobTitle": "",
    "phone": "",
    "email": "naodtedros@gmail.com",
    "location": "Mississauga, ON",
    "role": null
  },
  {
    "id": "1564602656301",
    "firstName": "steven",
    "lastName": "fletcher",
    "name": "steven fletcher",
    "description": "fletcherfocus",
    "jobTitle": "",
    "phone": "",
    "email": "stevenjohnfletcher@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564773034301",
    "firstName": "Idris",
    "lastName": "Oyelaja",
    "name": "Idris Oyelaja",
    "description": "IDRIS",
    "jobTitle": "",
    "phone": "",
    "email": "olayinks455@gmail.com",
    "location": "Winnipeg, MB",
    "role": "Volunteer"
  },
  {
    "id": "1564967910301",
    "firstName": "Johnny",
    "lastName": "Lee",
    "name": "Johnny Lee",
    "description": "University of Manitoba",
    "jobTitle": "Machine Learning Researcher",
    "phone": "",
    "email": "jleeee15@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1564969976301",
    "firstName": "Juan",
    "lastName": "Rempel",
    "name": "Juan Rempel",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "jeep.mudding+eventbrite@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565010560301",
    "firstName": "Angie",
    "lastName": "Gu",
    "name": "Angie Gu",
    "description": "N",
    "jobTitle": "Data analyst",
    "phone": "",
    "email": "xyannca@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1565012403301",
    "firstName": "Cassandra",
    "lastName": "Phung",
    "name": "Cassandra Phung",
    "description": "IG Wealth Management",
    "jobTitle": "AI Data Engineer",
    "phone": "",
    "email": "cassandra.phung@ig.ca",
    "location": "Toronto, ON",
    "role": "Volunteer"
  },
  {
    "id": "1565022493301",
    "firstName": "Abdulkareem",
    "lastName": "Moyo",
    "name": "Abdulkareem Moyo",
    "description": "moyo",
    "jobTitle": "Scrum master/Agile Delivery Lead",
    "phone": "",
    "email": "wcssynyt4q@privaterelay.appleid.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1565022752301",
    "firstName": "Gagandeep",
    "lastName": "Singh",
    "name": "Gagandeep Singh",
    "description": "Price Industries",
    "jobTitle": "Data Engineer",
    "phone": "",
    "email": "tocontactgagan@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565022753301",
    "firstName": "Tonmoy",
    "lastName": "Ghosh",
    "name": "Tonmoy Ghosh",
    "description": "Price Industries",
    "jobTitle": "Data Engineer",
    "phone": "",
    "email": "technicaltg007@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1565065314301",
    "firstName": "Eleonore",
    "lastName": "Heinrichs",
    "name": "Eleonore Heinrichs",
    "description": "University of Manitoba",
    "jobTitle": "Lead, Database and Reporting Analyst",
    "phone": "",
    "email": "eleonore.heinrichs@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": "Organizer"
  },
  {
    "id": "1565075709301",
    "firstName": "Chris",
    "lastName": "Swenson",
    "name": "Chris Swenson",
    "description": "Wawanesa Mutual Insurance",
    "jobTitle": "Senior Data Analyst",
    "phone": "",
    "email": "cswenson@wawanesa.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565093681301",
    "firstName": "Raza",
    "lastName": "J",
    "name": "Raza J",
    "description": "Wawanesa",
    "jobTitle": "Senior Solutions Analyst",
    "phone": "",
    "email": "rjamil@wawanesa.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565104570301",
    "firstName": "Anand",
    "lastName": "Velidi",
    "name": "Anand Velidi",
    "description": "Wawanesa Insurance",
    "jobTitle": "",
    "phone": "",
    "email": "avelidi@wawanesa.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565161869301",
    "firstName": "Olena",
    "lastName": "Shevchenko",
    "name": "Olena Shevchenko",
    "description": "Improving Winnipeg",
    "jobTitle": "Data Consultant",
    "phone": "",
    "email": "olena.shevchenko@improving.com",
    "location": "Winnipeg, MB",
    "role": "Organizer"
  },
  {
    "id": "1565185347301",
    "firstName": "Mohammad Alamgir",
    "lastName": "Chowdhury",
    "name": "Mohammad Alamgir Chowdhury",
    "description": "University of Manitoba",
    "jobTitle": "Research Assistant",
    "phone": "",
    "email": "chowdh62@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565197653301",
    "firstName": "Anthony",
    "lastName": "Bruneau-Cormier",
    "name": "Anthony Bruneau-Cormier",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "bruneau1@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565314651301",
    "firstName": "Ashley",
    "lastName": "Ashaka",
    "name": "Ashley Ashaka",
    "description": "Government of Manitoba / MBLL",
    "jobTitle": "IT Project Engineer",
    "phone": "",
    "email": "amirah.aesthetics@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565351128301",
    "firstName": "Azeez",
    "lastName": "Akinlade",
    "name": "Azeez Akinlade",
    "description": "AA",
    "jobTitle": "",
    "phone": "",
    "email": "azeez.akinlade01@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1565379696301",
    "firstName": "Kyungmin",
    "lastName": "Kim",
    "name": "Kyungmin Kim",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "ohcan911@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565397211301",
    "firstName": "Mayank",
    "lastName": "Kataria",
    "name": "Mayank Kataria",
    "description": "Shared Health",
    "jobTitle": "Workforce Analyst",
    "phone": "",
    "email": "mayankkataria194@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565398799301",
    "firstName": "Oluwatobi",
    "lastName": "Aruna",
    "name": "Oluwatobi Aruna",
    "description": "RRC",
    "jobTitle": "Student",
    "phone": "",
    "email": "arunaoluwatobi@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565491031301",
    "firstName": "Trudy",
    "lastName": "Moghaddam",
    "name": "Trudy Moghaddam",
    "description": "Johnston group",
    "jobTitle": "Team lead application developer",
    "phone": "",
    "email": "trudymog@gmail.com",
    "location": "Steinbach, MB",
    "role": null
  },
  {
    "id": "1565497365301",
    "firstName": "Ali",
    "lastName": "Moghaddam",
    "name": "Ali Moghaddam",
    "description": "Red River College Polytechnic",
    "jobTitle": "Instructor",
    "phone": "",
    "email": "amoghaddam4488@gmail.com",
    "location": "Steinbach, MB",
    "role": null
  },
  {
    "id": "1565539002301",
    "firstName": "Xiaoran",
    "lastName": "Meng",
    "name": "Xiaoran Meng",
    "description": "Pollard",
    "jobTitle": "",
    "phone": "",
    "email": "xrmeng720@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565905749301",
    "firstName": "kdc",
    "lastName": "cst",
    "name": "kdc cst",
    "description": "natapat",
    "jobTitle": "",
    "phone": "",
    "email": "tools@naturalpattern.space",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1565984189301",
    "firstName": "Ruben",
    "lastName": "Barrios",
    "name": "Ruben Barrios",
    "description": "Price Industries",
    "jobTitle": "Data Engineer",
    "phone": "",
    "email": "rabarrios25@gmail.com",
    "location": "Winnipeg, MB",
    "role": "Organizer"
  },
  {
    "id": "1566049441301",
    "firstName": "Ali",
    "lastName": "Ebadi",
    "name": "Ali Ebadi",
    "description": "The University of Winnipeg",
    "jobTitle": "Senior Research Assistant",
    "phone": "",
    "email": "ebadi-a@webmail.uwinnipeg.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566084036301",
    "firstName": "kdc",
    "lastName": "cst",
    "name": "kdc cst",
    "description": "natpat INCOSE",
    "jobTitle": "",
    "phone": "",
    "email": "tools@naturalpattern.space",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566086547301",
    "firstName": "Terry",
    "lastName": "Bunio",
    "name": "Terry Bunio",
    "description": "University of Manitoba",
    "jobTitle": "CIO",
    "phone": "",
    "email": "terry.bunio@umanitoba.ca",
    "location": "Winnipeg, MB",
    "role": "Organizer"
  },
  {
    "id": "1566114379301",
    "firstName": "Harmanjot",
    "lastName": "Kaur",
    "name": "Harmanjot Kaur",
    "description": "Red River College",
    "jobTitle": "Research Technologist",
    "phone": "",
    "email": "harmanjot082003@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566177025301",
    "firstName": "Junze",
    "lastName": "Zhou",
    "name": "Junze Zhou",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "lyo.eos@outlook.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566204760301",
    "firstName": "Fatema",
    "lastName": "Hossain",
    "name": "Fatema Hossain",
    "description": "N/A",
    "jobTitle": "",
    "phone": "",
    "email": "fatemahossain6837@gmail.com",
    "location": "Milton, ON",
    "role": null
  },
  {
    "id": "1566288242301",
    "firstName": "Destiny",
    "lastName": "Ovili",
    "name": "Destiny Ovili",
    "description": "Student",
    "jobTitle": "Student",
    "phone": "",
    "email": "destinyovili@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566352917301",
    "firstName": "Rakesh",
    "lastName": "Gurung",
    "name": "Rakesh Gurung",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "gurungr1@myumanitoba.ca",
    "location": "Brampton, ON",
    "role": "Volunteer"
  },
  {
    "id": "1566396120301",
    "firstName": "Pooja",
    "lastName": "Pawani",
    "name": "Pooja Pawani",
    "description": "Risepoint",
    "jobTitle": "Quality Assurance Leader",
    "phone": "",
    "email": "ppawani55@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566401042301",
    "firstName": "Daniel",
    "lastName": "Ochoa",
    "name": "Daniel Ochoa",
    "description": "Park West",
    "jobTitle": "Inventory",
    "phone": "",
    "email": "valenzuelad1@hotmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566474265301",
    "firstName": "Hunter",
    "lastName": "Ward",
    "name": "Hunter Ward",
    "description": "SYBS",
    "jobTitle": "Data scientist co-op student",
    "phone": "",
    "email": "wardhunter0@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566704343301",
    "firstName": "Jhon",
    "lastName": "Araujo",
    "name": "Jhon Araujo",
    "description": "Freelance",
    "jobTitle": "",
    "phone": "",
    "email": "jhonmer.araujo.79@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1566826196301",
    "firstName": "Abenezer",
    "lastName": "Mergia",
    "name": "Abenezer Mergia",
    "description": "Lectura Ai",
    "jobTitle": "Student",
    "phone": "",
    "email": "abenuabera@gmail.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1566868769301",
    "firstName": "Shashen",
    "lastName": "Mudaly",
    "name": "Shashen Mudaly",
    "description": "Norima Consulting",
    "jobTitle": "Solutions Architect",
    "phone": "",
    "email": "shashen@gmail.com",
    "location": "Brandon, MB",
    "role": null
  },
  {
    "id": "1567011840301",
    "firstName": "Liam",
    "lastName": "Elson",
    "name": "Liam Elson",
    "description": "Johnston Group",
    "jobTitle": "Data Analytics Developer",
    "phone": "",
    "email": "liamelson21@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567104771301",
    "firstName": "Agape",
    "lastName": "Seo",
    "name": "Agape Seo",
    "description": "Richardson International",
    "jobTitle": "",
    "phone": "",
    "email": "agapeseo@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567104922301",
    "firstName": "Grace",
    "lastName": "Seo",
    "name": "Grace Seo",
    "description": "Public Health Agency of Canada",
    "jobTitle": "",
    "phone": "",
    "email": "seo.grace.e@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567158596301",
    "firstName": "Hong Nhung",
    "lastName": "Pham",
    "name": "Hong Nhung Pham",
    "description": "UofW",
    "jobTitle": "",
    "phone": "",
    "email": "phamhongnhung2294@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567161383301",
    "firstName": "Hong",
    "lastName": "Pham",
    "name": "Hong Pham",
    "description": "U of Winnipeg",
    "jobTitle": "",
    "phone": "",
    "email": "phamhongnhung2294@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567163568301",
    "firstName": "sirath",
    "lastName": "vaid",
    "name": "sirath vaid",
    "description": "Student RRC",
    "jobTitle": "I am a student at Red river college and it is a great opportunity for me tomlear",
    "phone": "",
    "email": "vaidsirath11@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567243210301",
    "firstName": "Sheikh Safwan",
    "lastName": "Hossain",
    "name": "Sheikh Safwan Hossain",
    "description": "Intouchcx",
    "jobTitle": "",
    "phone": "",
    "email": "sakifhossain71@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567425111301",
    "firstName": "Nicolas",
    "lastName": "Subek Simon",
    "name": "Nicolas Subek Simon",
    "description": "New grad",
    "jobTitle": "SOC Analyst",
    "phone": "",
    "email": "subeks@tutanota.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567515737301",
    "firstName": "Tanvi",
    "lastName": "Patel",
    "name": "Tanvi Patel",
    "description": "University of Manitoba(student)",
    "jobTitle": "Student",
    "phone": "",
    "email": "tanvimp2004@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567577075301",
    "firstName": "Ariel",
    "lastName": "Jentsch",
    "name": "Ariel Jentsch",
    "description": "N/A",
    "jobTitle": "N/A",
    "phone": "",
    "email": "reali_arter@hotmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567577933301",
    "firstName": "Terra",
    "lastName": "Jentsch",
    "name": "Terra Jentsch",
    "description": "N/A",
    "jobTitle": "N/A",
    "phone": "",
    "email": "aurora_tj@hotmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567585943301",
    "firstName": "Aamena",
    "lastName": "Ghousy",
    "name": "Aamena Ghousy",
    "description": "CancerCare Manitoba",
    "jobTitle": "Data Analyst",
    "phone": "",
    "email": "aamena0928@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567654777301",
    "firstName": "An",
    "lastName": "Ho",
    "name": "An Ho",
    "description": "UofW",
    "jobTitle": "",
    "phone": "",
    "email": "anlac2359@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1567658907301",
    "firstName": "Kaneza",
    "lastName": "Louise",
    "name": "Kaneza Louise",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "rght74cgnt@privaterelay.appleid.com",
    "location": "Vancouver, BC",
    "role": null
  },
  {
    "id": "1567800533301",
    "firstName": "Anastasiia",
    "lastName": "Bohachenko",
    "name": "Anastasiia Bohachenko",
    "description": "University of Manitoba",
    "jobTitle": "Data Analyst",
    "phone": "",
    "email": "nastialetter@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568263115301",
    "firstName": "Linpu",
    "lastName": "Zhang",
    "name": "Linpu Zhang",
    "description": "University of Manitoba",
    "jobTitle": "Graduate",
    "phone": "",
    "email": "zhangl53@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568294256301",
    "firstName": "Nouran",
    "lastName": "Bileha",
    "name": "Nouran Bileha",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "bilehanouran@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568366734301",
    "firstName": "huilin",
    "lastName": "wang",
    "name": "huilin wang",
    "description": "iGM",
    "jobTitle": "data science intern at IGM",
    "phone": "",
    "email": "wangh1@myumanitoba.ca",
    "location": "Toronto, ON",
    "role": null
  },
  {
    "id": "1568382304301",
    "firstName": "Narek",
    "lastName": "Veranyan",
    "name": "Narek Veranyan",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "veranyan@myumanitoba.ca",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568409870301",
    "firstName": "Kobiljon",
    "lastName": "Erkinjonov",
    "name": "Kobiljon Erkinjonov",
    "description": "Student",
    "jobTitle": "Data Science student from University of Manitoba",
    "phone": "",
    "email": "erkinjonovqobiljon@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568412784301",
    "firstName": "Muhammad Sayid",
    "lastName": "Mamasiddikov",
    "name": "Muhammad Sayid Mamasiddikov",
    "description": "Student",
    "jobTitle": "Computer Science Student from University of Manitoba",
    "phone": "",
    "email": "claymrx003@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568431291301",
    "firstName": "Hritik",
    "lastName": "Punj",
    "name": "Hritik Punj",
    "description": "Norima Consulting",
    "jobTitle": "",
    "phone": "",
    "email": "hritikpunj@icloud.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568460092301",
    "firstName": "Ellie",
    "lastName": "Duong",
    "name": "Ellie Duong",
    "description": "GOM",
    "jobTitle": "IT Business Analyst",
    "phone": "",
    "email": "lyduong0910@gmail.com",
    "location": "Winnipeg, MB",
    "role": null
  },
  {
    "id": "1568663253301",
    "firstName": "Matthew",
    "lastName": "Fogel",
    "name": "Matthew Fogel",
    "description": "IG Wealth Management",
    "jobTitle": "Data Engineering Specialist",
    "phone": "",
    "email": "matthewfogel@outlook.com",
    "location": "BC",
    "role": null
  },
  {
    "id": "1568704287301",
    "firstName": "Sukhmandeep",
    "lastName": "Kaur",
    "name": "Sukhmandeep Kaur",
    "description": "IGM Financial/Financière IGM",
    "jobTitle": "Senior Data Engineer",
    "phone": "",
    "email": "sdkbhatti24@gmail.com",
    "location": "Toronto, ON",
    "role": null
  },
  {
    "id": "1552256183301",
    "firstName": "Roxana",
    "lastName": "Ibanez",
    "name": "Roxana Ibanez",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "roxana@winnipegedt.com",
    "location": "",
    "role": null
  },
  {
    "id": "1559977382301",
    "firstName": "Sukhmandeep",
    "lastName": "Kaur",
    "name": "Sukhmandeep Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "sukhman2807@gmail.com",
    "location": "",
    "role": null
  },
  {
    "id": "1564216459301",
    "firstName": "RITHIKA",
    "lastName": "NEMURI",
    "name": "RITHIKA NEMURI",
    "description": "inTouch CX",
    "jobTitle": "",
    "phone": "",
    "email": "rithika.nemuri@gmail.com",
    "location": "",
    "role": null
  },
  {
    "id": "242039476065953",
    "firstName": "Hadi",
    "lastName": "Abdul",
    "name": "Hadi Abdul",
    "description": "Software Engineer specializing in AWS cloud, data, search and AI solutions",
    "jobTitle": "",
    "phone": "2046983137",
    "email": "abdulhadi2122@gmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "332929937624195",
    "firstName": "Alex",
    "lastName": "Campomanes",
    "name": "Alex Campomanes",
    "description": "Executive Director of Advancement Services at the University of Manitoba",
    "jobTitle": "",
    "phone": "2042279218",
    "email": "alex.campomanes@umanitoba.ca",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "122650335860236",
    "firstName": "Anastasiia",
    "lastName": "Kasprova",
    "name": "Anastasiia Kasprova",
    "description": "Improving Winnipeg, Senior Consultant, PhD",
    "jobTitle": "",
    "phone": "",
    "email": "anastasiia.kasprova@gmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "287809484226994",
    "firstName": "Cesario",
    "lastName": "Estrada",
    "name": "Cesario Estrada",
    "description": "AI & Machine Learning Specialist | Data Solutions Developer",
    "jobTitle": "",
    "phone": "2043331097",
    "email": "cesarajjjume74@gmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "245481766348051",
    "firstName": "Darian",
    "lastName": "Lagman",
    "name": "Darian Lagman",
    "description": "Software Developer & Local AI Infrastructure Builder",
    "jobTitle": "",
    "phone": "2048073798",
    "email": "darjaylag@gmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "900000000000006",
    "firstName": "Eleonore",
    "lastName": "Braun",
    "name": "Eleonore Braun",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "eleonore.braun@gmail.com",
    "location": "",
    "role": "Volunteer"
  },
  {
    "id": "202978483805144",
    "firstName": "Greg",
    "lastName": "Peter-Joyal",
    "name": "Greg Peter-Joyal",
    "description": "Improving, Senior Consultant in Data Engineering",
    "jobTitle": "",
    "phone": "",
    "email": "gregjoyal@hotmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "187854514082655",
    "firstName": "Hannah",
    "lastName": "Vernon",
    "name": "Hannah Vernon",
    "description": "Senior Database Reliability Engineer | sqlserverscience.com",
    "jobTitle": "",
    "phone": "",
    "email": "hannah@mvct.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "283742104233699",
    "firstName": "Adam",
    "lastName": "Krieger",
    "name": "Adam Krieger",
    "description": "Security Architect, CISSP, CSSLP, CISA",
    "jobTitle": "",
    "phone": "2048805279",
    "email": "hello@adamkrieger.ca",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "321333801290122",
    "firstName": "Huzhi",
    "lastName": "Zhao",
    "name": "Huzhi Zhao",
    "description": "Backend & Data Engineer | Applied AI post-grad student, University of Winnipeg",
    "jobTitle": "",
    "phone": "2048810766",
    "email": "huzhi.zhao.smecta@gmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "171797940077593",
    "firstName": "Jennifer",
    "lastName": "Bodnarchuk",
    "name": "Jennifer Bodnarchuk",
    "description": "City of Winnipeg, Coordinator of Data & Analytics",
    "jobTitle": "",
    "phone": "",
    "email": "jbodnarchuk@winnipeg.ca",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "168657489392539",
    "firstName": "Karen",
    "lastName": "Lopez",
    "name": "Karen Lopez",
    "description": "Data Evangelist for InfoAdvisors, Space Enthusiast, & TeamData Coach",
    "jobTitle": "",
    "phone": "6472843404",
    "email": "KarenLopez@infoadvisors.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "168942086280814",
    "firstName": "Kate",
    "lastName": "Kehler",
    "name": "Kate Kehler",
    "description": "Social Planning Council of Winnipeg",
    "jobTitle": "",
    "phone": "",
    "email": "kkehler@spcw.mb.ca",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "170753873906323",
    "firstName": "Louis-Francois",
    "lastName": "Bouchard",
    "name": "Louis-Francois Bouchard",
    "description": "CTO & Co-Founder · Towards AI",
    "jobTitle": "",
    "phone": "",
    "email": "louis@towardsai.net",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "900000000000015",
    "firstName": "Mike",
    "lastName": "Diehl",
    "name": "Mike Diehl",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "Mike.Diehl@improving.com",
    "location": "",
    "role": "Organizer"
  },
  {
    "id": "275422777320055",
    "firstName": "Rick",
    "lastName": "Lowe",
    "name": "Rick Lowe",
    "description": "Data FLowe Solutions LLC",
    "jobTitle": "",
    "phone": "",
    "email": "rick@data-flowe.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "179857007835368",
    "firstName": "Sudhir",
    "lastName": "Amin",
    "name": "Sudhir Amin",
    "description": "Sr Database Specialist Solution Architect",
    "jobTitle": "",
    "phone": "",
    "email": "sudhamin@amazon.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "111863964707765",
    "firstName": "Temitope",
    "lastName": "Oladele (PhD)",
    "name": "Temitope Oladele (PhD)",
    "description": "Data Engineering, MDM, AI",
    "jobTitle": "",
    "phone": "2049957602",
    "email": "temitope.vistro@gmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "294218383854882",
    "firstName": "Thimantha",
    "lastName": "Vidanagamage",
    "name": "Thimantha Vidanagamage",
    "description": "Senior Data Engineer at OMERS, Canada",
    "jobTitle": "",
    "phone": "",
    "email": "thimantha.vidanagamage@hotmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "258259063723310",
    "firstName": "Trevor",
    "lastName": "Strome",
    "name": "Trevor Strome",
    "description": "Director, IT Operations and Data, Winnipeg Airports Authority",
    "jobTitle": "",
    "phone": "",
    "email": "tstrome@gmail.com",
    "location": "",
    "role": "Speaker"
  },
  {
    "id": "900000000000021",
    "firstName": "Wing",
    "lastName": "Kwong",
    "name": "Wing Kwong",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "wing.kwong@umanitoba.ca",
    "location": "",
    "role": "Organizer"
  }
]';

EXECUTE Scan.Update_Identities
    @EventCode = @EventCode,
    @EncryptionKey = @EncryptionKey,
    @Identities_blob = @Identities_blob;
GO