-- Generated from: Day_of_Data_Winnipeg_2026_Attendees_40554971420_20260907_181138_344.csv, report-2026-09-07T1312.csv
-- Idempotent ID rule: (Order ID * 100) + attendee sequence within that order.
-- Fill in @EventSecret before executing this script.

DECLARE @EventSecret uniqueidentifier = N'00000000-0000-0000-0000-000000000000';
DECLARE @EncryptionKey nvarchar(200) = N'';
DECLARE @Identities_blob nvarchar(max) = N'[
  {
    "id": "1541600395301",
    "firstName": "Oleksandr",
    "lastName": "Dimbrovskyi",
    "name": "Oleksandr Dimbrovskyi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "oleksandr.dimbrovskyi@gmail.com",
    "location": "BC"
  },
  {
    "id": "1542528276301",
    "firstName": "Bagdat",
    "lastName": "Rakhimov",
    "name": "Bagdat Rakhimov",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "bagdat.rakhimov@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1543694209301",
    "firstName": "wilfred",
    "lastName": "kamau   wairimu",
    "name": "wilfred kamau   wairimu",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "samuelkariithi123@gmail.com",
    "location": "Nairobi, 30"
  },
  {
    "id": "1545925283301",
    "firstName": "Maria",
    "lastName": "Besiada",
    "name": "Maria Besiada",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "xrmeng720@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1545925283302",
    "firstName": "Xiaoran",
    "lastName": "Meng",
    "name": "Xiaoran Meng",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "xrmeng720@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1551789838301",
    "firstName": "Cheryl",
    "lastName": "Hooper",
    "name": "Cheryl Hooper",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "cheryl@winnipegedt.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1552256183301",
    "firstName": "Roxana",
    "lastName": "Ibanez",
    "name": "Roxana Ibanez",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "roxana@winnipegedt.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1553574935301",
    "firstName": "Chiaka",
    "lastName": "Nosike",
    "name": "Chiaka Nosike",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "chiakanosike203@gmail.com",
    "location": "Toronto, ON"
  },
  {
    "id": "1553883222301",
    "firstName": "Juan",
    "lastName": "Villamizar",
    "name": "Juan Villamizar",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "jucamvil@hotmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1554162943301",
    "firstName": "Janelle Jaira",
    "lastName": "Mercado",
    "name": "Janelle Jaira Mercado",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "janjaimerc@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1555193018301",
    "firstName": "Richard",
    "lastName": "Essenyi",
    "name": "Richard Essenyi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ressenyi@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1558702137301",
    "firstName": "Tien",
    "lastName": "Huynh",
    "name": "Tien Huynh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "huynhntdl@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1558867735301",
    "firstName": "Scott",
    "lastName": "Stauffer",
    "name": "Scott Stauffer",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ScottAStauffer@Outlook.com",
    "location": "Surrey, BC"
  },
  {
    "id": "1559291070301",
    "firstName": "Carson",
    "lastName": "Leung",
    "name": "Carson Leung",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "carson.leung@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559310127301",
    "firstName": "Lang",
    "lastName": "G",
    "name": "Lang G",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "gonglange@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559312323301",
    "firstName": "Maria",
    "lastName": "besiada",
    "name": "Maria besiada",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "xrmeng720@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559312323302",
    "firstName": "Xiaoran",
    "lastName": "Meng",
    "name": "Xiaoran Meng",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "xrmeng720@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559348056301",
    "firstName": "Princess",
    "lastName": "Cortes",
    "name": "Princess Cortes",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "pcortes@rrc.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559375850301",
    "firstName": "Armaan Singh",
    "lastName": "Grover",
    "name": "Armaan Singh Grover",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "armaans.grover07@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559394126301",
    "firstName": "Hitesh",
    "lastName": "Nagpal",
    "name": "Hitesh Nagpal",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "hiteshnagpal955@gmail.com",
    "location": "Calgary, AB"
  },
  {
    "id": "1559419620301",
    "firstName": "Zainab",
    "lastName": "Hassan",
    "name": "Zainab Hassan",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "zainabmosunmola@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559420234301",
    "firstName": "Ali",
    "lastName": "Esmaeili",
    "name": "Ali Esmaeili",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "a.programming2022@gmail.com",
    "location": "Montreal, QC"
  },
  {
    "id": "1559529675301",
    "firstName": "Adeleke",
    "lastName": "Adenuga",
    "name": "Adeleke Adenuga",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "agbolade2020@gmail.com",
    "location": "ON"
  },
  {
    "id": "1559549143301",
    "firstName": "Baher",
    "lastName": "Alabbar",
    "name": "Baher Alabbar",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "baher.alabbar@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559556560301",
    "firstName": "Kavya",
    "lastName": "Bakshi",
    "name": "Kavya Bakshi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "bakshikavya143@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559563226301",
    "firstName": "Ravneet",
    "lastName": "Kaur",
    "name": "Ravneet Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ravneet1994@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559599169301",
    "firstName": "Dapinder",
    "lastName": "Kaur",
    "name": "Dapinder Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "gilldapinder515@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559624007301",
    "firstName": "Laleh",
    "lastName": "Asadzadeh",
    "name": "Laleh Asadzadeh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "la.asadzadeh@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559629544301",
    "firstName": "Bisola",
    "lastName": "Adebija",
    "name": "Bisola Adebija",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "bisolaadebija@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559656166301",
    "firstName": "Amir",
    "lastName": "Bani Saeed",
    "name": "Amir Bani Saeed",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "banisaea@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559681575301",
    "firstName": "Yang",
    "lastName": "Liu",
    "name": "Yang Liu",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "liuyang6093@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559692282301",
    "firstName": "Khadijat",
    "lastName": "Folarin",
    "name": "Khadijat Folarin",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "folarinko20@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559746442301",
    "firstName": "Scott",
    "lastName": "White",
    "name": "Scott White",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "7qwfk8pznm@privaterelay.appleid.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559904141301",
    "firstName": "Mohammad",
    "lastName": "Hassan",
    "name": "Mohammad Hassan",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "hasan.ahmed1435@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559968138301",
    "firstName": "Natasha",
    "lastName": "Williams",
    "name": "Natasha Williams",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "natashawilliams883@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1559977382301",
    "firstName": "Sukhmandeep",
    "lastName": "Kaur",
    "name": "Sukhmandeep Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "sukhman2807@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560012182301",
    "firstName": "Zahra",
    "lastName": "Nasresfahani",
    "name": "Zahra Nasresfahani",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "nasresfz@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560020388301",
    "firstName": "Zahra",
    "lastName": "Rizvi",
    "name": "Zahra Rizvi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "zahraxrizvi@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560024139301",
    "firstName": "Gurdarshan",
    "lastName": "Singh",
    "name": "Gurdarshan Singh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "singhgurdarshan715@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560025894301",
    "firstName": "Bagdat",
    "lastName": "Rakhimov",
    "name": "Bagdat Rakhimov",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "bagdat.rakhimov@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560025914301",
    "firstName": "Kurt",
    "lastName": "Huff",
    "name": "Kurt Huff",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "kurtljhuff@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560029003301",
    "firstName": "Jay",
    "lastName": "Dalool",
    "name": "Jay Dalool",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "jay16ca@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560055968301",
    "firstName": "Fawaz",
    "lastName": "Bin Saleem",
    "name": "Fawaz Bin Saleem",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "fawazbinsaleem2001@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560065224301",
    "firstName": "McCauley",
    "lastName": "Armishaw",
    "name": "McCauley Armishaw",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "mtarmishaw14@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560071352301",
    "firstName": "Emmanuel",
    "lastName": "Oyenuga",
    "name": "Emmanuel Oyenuga",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "emmaoyenuga@gmail.com",
    "location": "BC"
  },
  {
    "id": "1560075501301",
    "firstName": "Atishaya",
    "lastName": "Maharjan",
    "name": "Atishaya Maharjan",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "atishaya7777@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560116371301",
    "firstName": "Yirong",
    "lastName": "Wang",
    "name": "Yirong Wang",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "yw181920@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560117712301",
    "firstName": "Roshan",
    "lastName": "Chapagain",
    "name": "Roshan Chapagain",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "arobce@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560155242301",
    "firstName": "Simran",
    "lastName": "Panthi",
    "name": "Simran Panthi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "simranpanthi101@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560160030301",
    "firstName": "Faiza",
    "lastName": "Salami",
    "name": "Faiza Salami",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "salami.faiza15@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560224997301",
    "firstName": "Ramatjyot",
    "lastName": "Singh",
    "name": "Ramatjyot Singh",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ramatjyot13.ca@gmail.com",
    "location": "ON"
  },
  {
    "id": "1560226919301",
    "firstName": "Abdalla",
    "lastName": "Mohammed",
    "name": "Abdalla Mohammed",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "abdalla.mohd000@gmail.com",
    "location": "Etobicoke, ON"
  },
  {
    "id": "1560250008301",
    "firstName": "Kimi",
    "lastName": "Lin",
    "name": "Kimi Lin",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "kimibusiness@gmail.com",
    "location": "Etobicoke, ON"
  },
  {
    "id": "1560320034301",
    "firstName": "Pratham",
    "lastName": "Patel",
    "name": "Pratham Patel",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "adriftenigma@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560334536301",
    "firstName": "Gurneet",
    "lastName": "Kaur",
    "name": "Gurneet Kaur",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "kgurneet0224@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560423606301",
    "firstName": "Atul",
    "lastName": "Jha",
    "name": "Atul Jha",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ashandilya795@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560424807301",
    "firstName": "Shey",
    "lastName": "Porto",
    "name": "Shey Porto",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "sherylsuarezporto@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560492678301",
    "firstName": "Pam",
    "lastName": "Mollinedo",
    "name": "Pam Mollinedo",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "pamkmoll@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560520699301",
    "firstName": "Sarabjit",
    "lastName": "Sethi",
    "name": "Sarabjit Sethi",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "sarabjitsinghsethi85@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560536069301",
    "firstName": "Hasib",
    "lastName": "Pulok",
    "name": "Hasib Pulok",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "ahsanpulok999@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560586553301",
    "firstName": "Kismat",
    "lastName": "Ali",
    "name": "Kismat Ali",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "Alikismat2222@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560763969301",
    "firstName": "Logan",
    "lastName": "Decock",
    "name": "Logan Decock",
    "description": "",
    "jobTitle": "",
    "phone": "",
    "email": "logandecock004@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560790071301",
    "firstName": "Obafunsho",
    "lastName": "Thanni",
    "name": "Obafunsho Thanni",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "obafunshot@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560845800301",
    "firstName": "Kiet",
    "lastName": "QUach",
    "name": "Kiet QUach",
    "description": "ESDC",
    "jobTitle": "Senior Data Analyst",
    "phone": "",
    "email": "kquach@gmail.com",
    "location": "Ottawa, ON"
  },
  {
    "id": "1560847292301",
    "firstName": "jian",
    "lastName": "chen",
    "name": "jian chen",
    "description": "outreachgenius",
    "jobTitle": "",
    "phone": "",
    "email": "alanchenjain@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560859437301",
    "firstName": "Brenda",
    "lastName": "Stoesz",
    "name": "Brenda Stoesz",
    "description": "University of Manitoba",
    "jobTitle": "Portfolio Lead - Data, Evaluation, and Higher Education Research",
    "phone": "",
    "email": "brenda.stoesz@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560860972301",
    "firstName": "Viktoriia",
    "lastName": "Pylypets-Romaniuk",
    "name": "Viktoriia Pylypets-Romaniuk",
    "description": "Outlier",
    "jobTitle": "Data analyst",
    "phone": "",
    "email": "prviktoriia@gmail.com",
    "location": "Steinbach, MB"
  },
  {
    "id": "1560877241301",
    "firstName": "Mandy",
    "lastName": "Siragusa",
    "name": "Mandy Siragusa",
    "description": "University of Manitoba, Office of Rural and Remote Learner Experiences",
    "jobTitle": "",
    "phone": "",
    "email": "mandy.siragusa@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560905042301",
    "firstName": "Morgan",
    "lastName": "May",
    "name": "Morgan May",
    "description": "University of Manitoba - Engineering Makerspace",
    "jobTitle": "Maker of things, writer of codes, breaker of systems",
    "phone": "",
    "email": "morgan.may2@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1560920322301",
    "firstName": "Noel",
    "lastName": "Gelineau",
    "name": "Noel Gelineau",
    "description": "Manitoba Liquor and Lotteries Corporation",
    "jobTitle": "Data Governance Architect",
    "phone": "",
    "email": "noel.gelineau@gmail.com",
    "location": "Niverville, MB"
  },
  {
    "id": "1560948260301",
    "firstName": "Binita",
    "lastName": "Shetty",
    "name": "Binita Shetty",
    "description": "University of Manitoba",
    "jobTitle": "Senior Analyst",
    "phone": "",
    "email": "Shettyb@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561032486301",
    "firstName": "Andrey",
    "lastName": "Rybak",
    "name": "Andrey Rybak",
    "description": "Hrove labs",
    "jobTitle": "Founder",
    "phone": "",
    "email": "naonennenets@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561052450301",
    "firstName": "Olivia",
    "lastName": "Lee",
    "name": "Olivia Lee",
    "description": "University of Manitoba",
    "jobTitle": "Researcher",
    "phone": "",
    "email": "olivia.lee@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561085718301",
    "firstName": "Marcus",
    "lastName": "Hlady",
    "name": "Marcus Hlady",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "hlady.marcus@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561086958301",
    "firstName": "Gurrajan",
    "lastName": "Sharma",
    "name": "Gurrajan Sharma",
    "description": "Faculty of Science",
    "jobTitle": "Student",
    "phone": "",
    "email": "shar179@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561099062301",
    "firstName": "Karen",
    "lastName": "Masambaji",
    "name": "Karen Masambaji",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "karenupendo@gmail.com",
    "location": ""
  },
  {
    "id": "1561106479301",
    "firstName": "Janette",
    "lastName": "Suherli",
    "name": "Janette Suherli",
    "description": "University of Manitoba",
    "jobTitle": "Graduate Student",
    "phone": "",
    "email": "suherlij@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561108722301",
    "firstName": "Anthony",
    "lastName": "Okolie",
    "name": "Anthony Okolie",
    "description": "N/a",
    "jobTitle": "",
    "phone": "",
    "email": "anthonyokolie.ace@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561207709301",
    "firstName": "Nicholas",
    "lastName": "Tan",
    "name": "Nicholas Tan",
    "description": "UofM student",
    "jobTitle": "Student",
    "phone": "",
    "email": "tannjh@myumanitoba.ca",
    "location": "Singapore"
  },
  {
    "id": "1561271894301",
    "firstName": "Minori",
    "lastName": "Shibuya",
    "name": "Minori Shibuya",
    "description": "Uofm",
    "jobTitle": "",
    "phone": "",
    "email": "zibanyan1222@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561273694301",
    "firstName": "Minori",
    "lastName": "Shibuya",
    "name": "Minori Shibuya",
    "description": "Uofm",
    "jobTitle": "Student",
    "phone": "",
    "email": "zibanyan1222@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561278334301",
    "firstName": "Jatinder",
    "lastName": "Sahota",
    "name": "Jatinder Sahota",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "jatindersahota2184@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561291694301",
    "firstName": "Jeet",
    "lastName": "Rajvanshi",
    "name": "Jeet Rajvanshi",
    "description": "student",
    "jobTitle": "",
    "phone": "",
    "email": "jeetdhruv2003@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561474878301",
    "firstName": "Gurjit",
    "lastName": "Singh",
    "name": "Gurjit Singh",
    "description": "NA",
    "jobTitle": "PMO Manager",
    "phone": "",
    "email": "guruhayat@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561504465301",
    "firstName": "Amro",
    "lastName": "Hamid",
    "name": "Amro Hamid",
    "description": "N''Dinawemak",
    "jobTitle": "Digital Transformation and Operations Excellence Manager",
    "phone": "",
    "email": "alshukairi.al@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561536712301",
    "firstName": "Chidiebere Gregory",
    "lastName": "Uduh",
    "name": "Chidiebere Gregory Uduh",
    "description": "Bejite",
    "jobTitle": "DevOps Lead",
    "phone": "",
    "email": "udugreg@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561539580301",
    "firstName": "Seyedsaber",
    "lastName": "Mirmiran",
    "name": "Seyedsaber Mirmiran",
    "description": "University of Manitoba",
    "jobTitle": "Application Developer",
    "phone": "",
    "email": "seyedsaber.mirmiran@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561541794301",
    "firstName": "Mohammad",
    "lastName": "Hassan",
    "name": "Mohammad Hassan",
    "description": "University of Winnipeg",
    "jobTitle": "Research Assistant",
    "phone": "",
    "email": "hasan.ahmed1435@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561593626301",
    "firstName": "Sofia",
    "lastName": "Dumas",
    "name": "Sofia Dumas",
    "description": "IG Wealth Management",
    "jobTitle": "Software Developer",
    "phone": "",
    "email": "dumas.mariasofia@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561597058301",
    "firstName": "Shivanshu",
    "lastName": "Sharma",
    "name": "Shivanshu Sharma",
    "description": "Price Industries",
    "jobTitle": "Data Engineer",
    "phone": "",
    "email": "shivanshu.mps@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561598801301",
    "firstName": "Ramandeep",
    "lastName": "Kaur",
    "name": "Ramandeep Kaur",
    "description": "University of Manitoba",
    "jobTitle": "Database and Reporting Analyst",
    "phone": "",
    "email": "Ramandeep.Kaur1@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561601890301",
    "firstName": "Anika",
    "lastName": "Viado",
    "name": "Anika Viado",
    "description": "Red River College (Student)",
    "jobTitle": "Student",
    "phone": "",
    "email": "anikaviado@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561605395301",
    "firstName": "Vanessa",
    "lastName": "Castro",
    "name": "Vanessa Castro",
    "description": "Red River Polytechnic College - Student",
    "jobTitle": "Student",
    "phone": "",
    "email": "ayla.buenafe88@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561605545301",
    "firstName": "Vance Alden",
    "lastName": "Castro",
    "name": "Vance Alden Castro",
    "description": "Red River College Polytechnic",
    "jobTitle": "Student",
    "phone": "",
    "email": "vcastro2@rrc.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561612659301",
    "firstName": "Tatiana",
    "lastName": "Varlamova",
    "name": "Tatiana Varlamova",
    "description": "Norima Consulting",
    "jobTitle": "",
    "phone": "",
    "email": "varlamova.com@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561612816301",
    "firstName": "Oleksiy",
    "lastName": "Dolgykh",
    "name": "Oleksiy Dolgykh",
    "description": "Individual Researcher",
    "jobTitle": "AI/ML Researcher/Manager",
    "phone": "",
    "email": "alexey.dolgich@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561621631301",
    "firstName": "Utsav",
    "lastName": "Panchal",
    "name": "Utsav Panchal",
    "description": "Manitoba Public Insurance",
    "jobTitle": "Supervisor - Cloud Infrastructure",
    "phone": "",
    "email": "utpanc@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561628903301",
    "firstName": "Sarabjit",
    "lastName": "Sethi",
    "name": "Sarabjit Sethi",
    "description": "MPI",
    "jobTitle": "Data Transformation Specialist",
    "phone": "",
    "email": "sarabjitsinghsethi85@gmail.com",
    "location": "ON"
  },
  {
    "id": "1561659482301",
    "firstName": "Mariya",
    "lastName": "Salamatova",
    "name": "Mariya Salamatova",
    "description": "Bird Construction",
    "jobTitle": "Senior Data Architect",
    "phone": "",
    "email": "salmarnic@gmail.com",
    "location": "BC"
  },
  {
    "id": "1561671324301",
    "firstName": "Gustavo",
    "lastName": "Dayrell",
    "name": "Gustavo Dayrell",
    "description": "IG Financial",
    "jobTitle": "Data Engineering Specialist",
    "phone": "",
    "email": "gusdayrell@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561676708301",
    "firstName": "Ali",
    "lastName": "Rezaei",
    "name": "Ali Rezaei",
    "description": "Manitoba Hydro",
    "jobTitle": "Load Forecast specialist",
    "phone": "",
    "email": "ali.rezaei.ee@gmail.com",
    "location": "BC"
  },
  {
    "id": "1561680804301",
    "firstName": "Shehani",
    "lastName": "Ranasinghe",
    "name": "Shehani Ranasinghe",
    "description": "Red River college",
    "jobTitle": "Student",
    "phone": "",
    "email": "shehanidinithi89@gmail.com",
    "location": "BC"
  },
  {
    "id": "1561682321301",
    "firstName": "Tuan",
    "lastName": "Le Dinh",
    "name": "Tuan Le Dinh",
    "description": "IG Wealth Management",
    "jobTitle": "Data Engineering Specialist",
    "phone": "",
    "email": "9fkws8czsy@privaterelay.appleid.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561703115301",
    "firstName": "Sohvat",
    "lastName": "Saini",
    "name": "Sohvat Saini",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "sainis2@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561703502301",
    "firstName": "Simi",
    "lastName": "Adeniyi",
    "name": "Simi Adeniyi",
    "description": "Student",
    "jobTitle": "",
    "phone": "",
    "email": "simiadeniyi97@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561723010301",
    "firstName": "Sethulakshmi",
    "lastName": "K Sajeev",
    "name": "Sethulakshmi K Sajeev",
    "description": "University of Manitoba",
    "jobTitle": "Research Analyst",
    "phone": "",
    "email": "seth.kumbalathuparambilsajeev@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561793106301",
    "firstName": "Pegah",
    "lastName": "Geranmayehkashani",
    "name": "Pegah Geranmayehkashani",
    "description": "Price Industries",
    "jobTitle": "",
    "phone": "",
    "email": "pegah.geranmayeh@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561805494301",
    "firstName": "Swastik",
    "lastName": "Dash",
    "name": "Swastik Dash",
    "description": "Student at University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "helloswastikdash@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561810993301",
    "firstName": "Byron",
    "lastName": "Wright",
    "name": "Byron Wright",
    "description": "Asper School of Business - U of M",
    "jobTitle": "MIS Instructor",
    "phone": "",
    "email": "byron.wright@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561850122301",
    "firstName": "Sai Sumanth",
    "lastName": "Mellacheruvu",
    "name": "Sai Sumanth Mellacheruvu",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "sumanthmellacheruvu@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561851119301",
    "firstName": "Emily",
    "lastName": "Clyde-Parry Yaroszko",
    "name": "Emily Clyde-Parry Yaroszko",
    "description": "University of Manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "yaroszko@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561868662301",
    "firstName": "Thuan Khang",
    "lastName": "Dinh",
    "name": "Thuan Khang Dinh",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "matthuanphong@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561894925301",
    "firstName": "Shelly",
    "lastName": "Smith",
    "name": "Shelly Smith",
    "description": "ARMA Canada",
    "jobTitle": "Information and Privacy Manager",
    "phone": "",
    "email": "shellybsmith@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561900576301",
    "firstName": "Arturo",
    "lastName": "Barrios",
    "name": "Arturo Barrios",
    "description": "Enalta",
    "jobTitle": "",
    "phone": "",
    "email": "abarriosdc@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561911048301",
    "firstName": "Subhash",
    "lastName": "Yadav",
    "name": "Subhash Yadav",
    "description": "university of manitoba",
    "jobTitle": "",
    "phone": "",
    "email": "yadavs2@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1561913300301",
    "firstName": "Faith",
    "lastName": "Akinyemi",
    "name": "Faith Akinyemi",
    "description": "GOM",
    "jobTitle": "",
    "phone": "",
    "email": "faithakinyemi01@gmail.com",
    "location": "Calgary, AB"
  },
  {
    "id": "1562012658301",
    "firstName": "Emma",
    "lastName": "Yang",
    "name": "Emma Yang",
    "description": "princessauto",
    "jobTitle": "",
    "phone": "",
    "email": "fxyflttw@hotmail.com",
    "location": "BC"
  },
  {
    "id": "1562103995301",
    "firstName": "Daniel",
    "lastName": "Mai",
    "name": "Daniel Mai",
    "description": "PolicyMe",
    "jobTitle": "",
    "phone": "",
    "email": "danielmai12.cs@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562252172301",
    "firstName": "Moon Jung",
    "lastName": "PERSSON",
    "name": "Moon Jung PERSSON",
    "description": "MB HYDRO",
    "jobTitle": "Tech. Assistance",
    "phone": "",
    "email": "ypersson@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562260224301",
    "firstName": "Erik",
    "lastName": "Persson",
    "name": "Erik Persson",
    "description": "Mvsd",
    "jobTitle": "Educator",
    "phone": "",
    "email": "espersson@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562331685301",
    "firstName": "Christopher",
    "lastName": "Duguay",
    "name": "Christopher Duguay",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "umdugua2@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562358005301",
    "firstName": "Navroop",
    "lastName": "Kaur",
    "name": "Navroop Kaur",
    "description": "RRC Polytechnic",
    "jobTitle": "Student",
    "phone": "",
    "email": "navroopkaur26@yahoo.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562448071301",
    "firstName": "Edwin Josue",
    "lastName": "Saltos Narvaez",
    "name": "Edwin Josue Saltos Narvaez",
    "description": "RRC",
    "jobTitle": "IT",
    "phone": "",
    "email": "esaltosnarvaez@academic.rrc.ca",
    "location": "Montreal, QC"
  },
  {
    "id": "1562584454301",
    "firstName": "KEIKO",
    "lastName": "HURTADO ANAMPA",
    "name": "KEIKO HURTADO ANAMPA",
    "description": "Student",
    "jobTitle": "Business intelligence analyst",
    "phone": "",
    "email": "hurtadok@myumanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562590552301",
    "firstName": "Demisew",
    "lastName": "Mengistu",
    "name": "Demisew Mengistu",
    "description": "WCB Manitoba",
    "jobTitle": "cloud engineer",
    "phone": "",
    "email": "mailtodemis08@gmail.com",
    "location": "BC"
  },
  {
    "id": "1562609928301",
    "firstName": "Ian",
    "lastName": "Smith",
    "name": "Ian Smith",
    "description": "Payworks",
    "jobTitle": "",
    "phone": "",
    "email": "ian.smith.12a@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562615225301",
    "firstName": "Evan",
    "lastName": "Penner",
    "name": "Evan Penner",
    "description": "Aimsio",
    "jobTitle": "Software Developer",
    "phone": "",
    "email": "evan.penner@aimsio.com",
    "location": "Kleefeld, MB"
  },
  {
    "id": "1562618106301",
    "firstName": "Ghazanfar",
    "lastName": "Abidi",
    "name": "Ghazanfar Abidi",
    "description": "Exchange Technology Services",
    "jobTitle": "Director Business Intelligence",
    "phone": "",
    "email": "ghazanfarjawed@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562621035301",
    "firstName": "Chris",
    "lastName": "Mac",
    "name": "Chris Mac",
    "description": "RRC Polytech",
    "jobTitle": "Instructor",
    "phone": "",
    "email": "chris@macmac.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562625614301",
    "firstName": "Mathieu",
    "lastName": "Sawatzky",
    "name": "Mathieu Sawatzky",
    "description": "Stride Credit Union",
    "jobTitle": "Data Analyst",
    "phone": "",
    "email": "matsawatzky@gmail.com",
    "location": "Toronto, ON"
  },
  {
    "id": "1562626086301",
    "firstName": "Barakat",
    "lastName": "Akinsanya-Fadairo",
    "name": "Barakat Akinsanya-Fadairo",
    "description": "WRHA",
    "jobTitle": "Business Analyst",
    "phone": "",
    "email": "bakkyinspiration@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562630002301",
    "firstName": "Upneesh",
    "lastName": "Thakur",
    "name": "Upneesh Thakur",
    "description": "Exchange Technology Services",
    "jobTitle": "Manager, Analytics",
    "phone": "",
    "email": "uthakur@exchangetech.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562642121301",
    "firstName": "Spencer",
    "lastName": "McDonald",
    "name": "Spencer McDonald",
    "description": "EPLS Group",
    "jobTitle": "IT Manager",
    "phone": "",
    "email": "spencer.c.mcdonald@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562644561301",
    "firstName": "Ashlean",
    "lastName": "Sterling",
    "name": "Ashlean Sterling",
    "description": "ByAshlean",
    "jobTitle": "Freelancer",
    "phone": "",
    "email": "ashlean.sterling@icloud.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562670906301",
    "firstName": "Gabriel",
    "lastName": "Nazario",
    "name": "Gabriel Nazario",
    "description": "Oag mb",
    "jobTitle": "Data analyst manager",
    "phone": "",
    "email": "nazariogabrielfarias@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562698709301",
    "firstName": "Nima",
    "lastName": "Geran Malek",
    "name": "Nima Geran Malek",
    "description": "Micro Tools & Machines",
    "jobTitle": "Manufacturing Engineer",
    "phone": "",
    "email": "nima.geran@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562745463301",
    "firstName": "Harshvardhan",
    "lastName": "Gadhavi",
    "name": "Harshvardhan Gadhavi",
    "description": "Pearle Vision",
    "jobTitle": "sales associate",
    "phone": "",
    "email": "harshvardhan@gadhvi.xyz",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562746922301",
    "firstName": "Cyril",
    "lastName": "Li",
    "name": "Cyril Li",
    "description": "Student",
    "jobTitle": "Student",
    "phone": "",
    "email": "cyrils.li@icloud.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562767859301",
    "firstName": "Guadalupe",
    "lastName": "Ricagno",
    "name": "Guadalupe Ricagno",
    "description": "Red River Mutual",
    "jobTitle": "HR Analytics",
    "phone": "",
    "email": "gricagno@redrivermutual.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562786892301",
    "firstName": "Kyle",
    "lastName": "Bain",
    "name": "Kyle Bain",
    "description": "Johnston Group",
    "jobTitle": "Manager, Data & Analytics",
    "phone": "",
    "email": "kylejennb@gmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1562957600301",
    "firstName": "Farzana",
    "lastName": "Ebrahim",
    "name": "Farzana Ebrahim",
    "description": "University of Manitoba",
    "jobTitle": "Senior Developer, Digital Learning Environments",
    "phone": "",
    "email": "farzana.ebrahim@umanitoba.ca",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1563027544301",
    "firstName": "Nathan",
    "lastName": "Da Silva",
    "name": "Nathan Da Silva",
    "description": "Chico''s Computers",
    "jobTitle": "Owner/Lead Technician",
    "phone": "",
    "email": "nathan.dasilva@hotmail.com",
    "location": "Winnipeg, MB"
  },
  {
    "id": "1563227158301",
    "firstName": "Arthur",
    "lastName": "Rangel",
    "name": "Arthur Rangel",
    "description": "Personal",
    "jobTitle": "ThinkLeader",
    "phone": "",
    "email": "yizus.rangel@gmail.com",
    "location": ""
  },
  {
    "id": "1563000108301",
    "firstName": "Lealdo",
    "lastName": "Andrade",
    "name": "Lealdo Andrade",
    "description": "Intouch Insight",
    "jobTitle": "",
    "phone": "",
    "email": "lealdo.gois.andrade@gmail.com",
    "location": ""
  },
  {
    "id": "1563358415301",
    "firstName": "Kijandi Pierre",
    "lastName": "Niyungeko",
    "name": "Kijandi Pierre Niyungeko",
    "description": "Pierre PC Repair Inc.",
    "jobTitle": "IT Support Specialist",
    "phone": "",
    "email": "pierrekijandi@hotmail.com",
    "location": ""
  },
  {
    "id": "1563510519301",
    "firstName": "Peter",
    "lastName": "Vu",
    "name": "Peter Vu",
    "description": "University of Manitoba",
    "jobTitle": "Student",
    "phone": "",
    "email": "peter.vu298@gmail.com",
    "location": ""
  },
  {
    "id": "1563642957301",
    "firstName": "Andrea",
    "lastName": "Sanchez",
    "name": "Andrea Sanchez",
    "description": "Freelancer",
    "jobTitle": "Microsoft Data Analyst - AzureDataFactory, with 5 years of experience in the Mic",
    "phone": "",
    "email": "andrealsanchez2018@gmail.com",
    "location": ""
  }
]';

EXECUTE Scan.Update_Identities
    @EventSecret = @EventSecret,
    @EncryptionKey = @EncryptionKey,
    @Identities_blob = @Identities_blob;
GO